{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbv.fullname" . }}
  labels:
    {{- include "dbv.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.config.mongodbUri | required "config.mongodbUri is required" | quote }}
{{- end }}
